### ISSUE TITLE
PDK 1.16.0.[12] doesn't work

### ISSUE THREAD

**Issue by jby** [puppetlabs/homebrew-puppet#169]
## Describe the Bug
After a fresh install of pdk 1.16.0.2:

```
 ~/Downloads  brew info pdk
Error: No available formula with the name "pdk"
Found a cask named "pdk" instead.

pdk: 1.16.0.2
https://github.com/puppetlabs/pdk
/usr/local/Caskroom/pdk/1.16.0.2 (268.4MB)
From: https://github.com/puppetlabs/homebrew-puppet/blob/master/Casks/pdk.rb
==> Name
Puppet Development Kit
==> Artifacts
pdk-1.16.0.2-1-installer.pkg (Pkg)
==> Caveats

    PDK binaries are installed in /opt/puppetlabs/pdk/bin, which is sourced by an /etc/paths.d entry.
    /opt/puppetlabs/pdk/bin may not be included in your current $PATH but should be included in new shells.


 !  ~/Downloads  pdk --version
/opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/core_ext/kernel_warn (LoadError)
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/puppetlabs/pdk/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems.rb:1395:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
 !  ~/Downloads 
```
 

## Expected Behavior
Working PDK

## Steps to Reproduce
See steps in code above

## Environment
 - Version 1.16.0.2
 - Platform macOS 10.15.3

**Comment by jby** [comment]
VS Code puppet extension complains about anything older than 1.16.0.2 is out of date, but as seen above 1.16.0.2 doesn't work - and neither does 1.16.0.1.
1.15.0.0 however does, but then VSC complains about it being out of date:
```
pdk --version
1.15.0
```

**Comment by scotje** [comment]
Hello! 1.16.0.1 was broken due to a permissions issue and unfortunately the macOS package installer can't quite fix it by simply installing the new version. The procedure outlined in this comment should resolve things: https://github.com/puppetlabs/pdk/issues/850#issuecomment-585319149

**Comment by jby** [comment]
Ah, crap left behind by 1.16.0.1 - didn't know that. 1.16.0.2 **does** work! Thank you!
