### ISSUE TITLE
404 installing puppet-bolt

### ISSUE THREAD

**Issue by wintermanc3r** [puppetlabs/homebrew-puppet#242]
## Describe the Bug

Heya; I'm unable to install newest puppet-bolt with brew:

> ==> Downloading https://downloads.puppet.com/mac/puppet/10.15/x86_64/puppet-bolt-2.35.0-1.osx10.15.dmg
> #=#=#
> curl: (22) The requested URL returned error: 404
> ==> Purging files for version 2.35.0 of Cask puppet-bolt
> Error: puppetlabs/puppet/puppet-bolt: Download failed on Cask 'puppet-bolt' with message: Download failed: https://downloads.puppet.com/mac/puppet/10.15/x86_64/puppet-bolt-2.35.0-1.osx10.15.dmg

This appears to be a legitimate error message, as 2.34.0 [seems to be present in that directory](https://downloads.puppet.com/mac/puppet/10.15/x86_64/), but not 2.35.0.

## Expected Behavior
Expected to be able to install it.

## Steps to Reproduce
1. Run `brew upgrade puppet-bolt` in a terminal.

## Environment
I'm running macOS Catalina, though I assume it also impacts 10.14 as 2.34 is not present here either: https://downloads.puppet.com/mac/puppet/10.14/x86_64/

**Comment by MikaelSmith** [comment]
@beechtom know any issues with rolling out the 2.35 release?

**Comment by MikaelSmith** [comment]
This appears to be fallout from the Puppet 7 platform rollout. If you swap `puppet` to `puppet6` the links work. Getting some folks to look at it to decide how we want to fix it.

**Comment by MikaelSmith** [comment]
Should now be fixed.
