### ISSUE TITLE
puppet-bolt can't be installed on arm64

### ISSUE THREAD

**Issue by tdsmith** [puppetlabs/homebrew-puppet#367]
`brew install puppetlabs/puppet/puppet-bolt` fails on arm64 machines after #365 with a message like:

```
==> Purging files for version 3.26.2 of Cask puppet-bolt
Error: puppetlabs/puppet/puppet-bolt: Download failed on Cask 'puppet-bolt' with message: Download failed: https://downloads.puppet.com/mac/puppet-tools/12/arm64/puppet-bolt-3.26.2-1.osx12.dmg
```

**Comment by donoghuc** [comment]
@tdsmith Can you confirm that bolt 3.26.1 was working on your ARM machine? I have heard from someone else today that they have x86 emulation enabled on an M1 mac that works for bolt. If so I can just get https://github.com/puppetlabs/homebrew-puppet/pull/368 merged while we work on getting builds for ARM for bolt packages.

**Comment by tdsmith** [comment]
Thanks! Prior versions were working fine under Rosetta 2, though I can’t promise I was on exactly that micro version.

**Comment by donoghuc** [comment]
Ah, right on. Was able to get an M1 vm and install rosetta on it. Bolt seems to be working in that env! Appreciate the report. Cheers

**Comment by donoghuc** [comment]
Should be fixed with https://github.com/puppetlabs/homebrew-puppet/pull/368 We will look in to actually building packages for ARM later.
