### ISSUE TITLE
`discontinued` is deprecated

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/homebrew-puppet#404]
## Describe the Bug
When puppet casks are updated, a warning is issued:
```
Warning: Calling `caveats :discontinued` is deprecated! Use `deprecate!` instead.
```

## Expected Behavior
According to the documentation, the following should be used to deprecate a formula
https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae
```
deprecate! date: "2023-04-05", because: "puppet6 went end-of-life at the end of February 2023"
```

**Comment by mhashizume** [comment]
Thanks for reporting this!
