### ISSUE TITLE
PDK installation hangs on macOS Mojave

### ISSUE THREAD

**Issue by julianxhokaxhiu** [puppetlabs/homebrew-puppet#68]
Hi,

I'm trying to install the PDK package through Homebrew on macOS Mojave and it looks like the installation hangs at some point.

This is the current output once I run the install command:
```sh
$ brew cask install puppetlabs/puppet/pdk
Updating Homebrew...
==> Caveats

    PDK binaries are installed in /opt/puppetlabs/pdk/bin, which is sourced by an /etc/paths.d entry.
    /opt/puppetlabs/pdk/bin may not be included in your current $PATH but should be included in new shells.

==> Satisfying dependencies
==> Downloading https://downloads.puppet.com/mac/puppet5/10.14/x86_64/pdk-1.10.0.0-1.osx10.14.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'pdk'.
==> Installing Cask pdk
```

Any help in debugging this would be helpful.

Thank you in advance,
Julian

**Comment by MikaelSmith** [comment]
I haven't had this happen (on Mojave), but I have had it take several minutes to perform the install.

There may be some install logs for the pdk installer. I'll see if I can find them when I have more time later.

**Comment by MikaelSmith** [comment]
`/var/log/install.log` may have some messages related to it.

**Comment by scotje** [comment]
Just did a test install on a clean Mojave instance and it took about 76 seconds to install the package, but it completely successfully.

**Comment by julianxhokaxhiu** [comment]
I did retry this morning ( Europe/Madrid timezone ) and it worked just fine this time, asking my Sudo password as I expected. For some unknown reason to me the machine was behaving weird yesterday.

Thanks to everyone for the support :)
